stages:
  - build

build binary:
  stage: build
  image: golang:1.19-alpine3.17
  script:
    - apk add --no-cache make git build-base
    - make
  artifacts:
    paths:
      - pod-info
      - main.html