stages:
  - build
  - package
  - test
  - deploy

variables:
  APP_VERSION: $CI_PIPELINE_IID-$CI_COMMIT_SHORT_SHA

.build binary:
  stage: build
  image: golang:1.19-alpine3.17
  script:
    - apk add --no-cache make git build-base gettext
    - mkdir build
    - envsubst < main.html > build/main.html
    - make
  artifacts:
    paths:
      - build

.docker build:
  stage: package
  services:
    - docker:23.0.4-dind
  image: docker:23.0.4
  script:
    - apk add curl
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker build -t $CI_REGISTRY_IMAGE -t $CI_REGISTRY_IMAGE:$APP_VERSION .
    - docker image ls
    - docker push --all-tags $CI_REGISTRY_IMAGE

.integration tests:
  stage: test
  services:
    - name: $CI_REGISTRY_IMAGE:$APP_VERSION
      alias: app
  image: curlimages/curl
  script:
    - curl http://app:8080 | grep $APP_VERSION

create merge request:
  stage: deploy
  image: 
    name: alpine/git:2.36.3
    entrypoint: [""]
  variables:
    TARGET_REPO_DEFAULT_BRANCH: master
  script:
    # to be able to use the CI_JOB_TOKEN the pure-gitops project must add the pod-info-app project to its allowlist -
    # that is not needed for public or internal projects
    # the CI_JOB_TOKEN has only read access to the repository
    # a personal access token needs to be created and a PERSONAL_ACCESS_TOKEN CI/CD variable
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/kyriakos_tsalia/pure-gitops
    - cd pure-gitops
    - git checkout -b feature/app-version_$APP_VERSION
    - sed -i "s#registry.gitlab.com.*#$CI_REGISTRY_IMAGE:${APP_VERSION}#g" manifests/deployment.yaml
    - grep image manifests/deployment.yaml
    - git add .
    - git config --global user.name $GITLAB_USER_NAME
    - git config --global user.email $GITLAB_USER_EMAIL
    - git commit -m "updated image version to ${APP_VERSION}"
    - git push -o merge_request.create -o merge_request.target=$TARGET_REPO_DEFAULT_BRANCH -o merge_request.title="Update application version to ${APP_VERSION}" -o merge_request.remove_source_branch https://$GITLAB_USER_LOGIN:$PERSONAL_ACCESS_TOKEN@gitlab.com/kyriakos_tsalia/pure-gitops feature/app-version_$APP_VERSION
