stages:
  - build
  - package

variables:
  APP_VERSION: $CI_PIPELINE_IID-$CI_COMMIT_SHORT_SHA

build binary:
  stage: build
  image: golang:1.19-alpine3.17
  script:
    - apk add --no-cache make git build-base gettext
    - mkdir build
    - envsubst < main.html > build/main.html
    - make
  artifacts:
    paths:
      - build

docker build:
  stage: package
  services:
    - docker:23.0.4-dind
  image: docker:23.0.4
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker build -t $CI_REGISTRY_IMAGE -t $CI_REGISTRY_IMAGE:$APP_VERSION .
    - docker image ls
    - docker run -d -p 8080:8080 $CI_REGISTRY_IMAGE:$APP_VERSION
    - sleep 10
    - curl http://localhost:8080 | grep $APP_VERSION
